name: Reusable workflow

on:
  workflow_dispatch:
    inputs:
      tmin:
        type: number  
        required: true
        
jobs:
  example_job:
    name: Generate output
    runs-on: ubuntu-latest
    steps:
    - timeout-minutes: ${{fromJSON(inputs.tmin)}}
      run: echo "hello"
