name: Close Pull Request

# only trigger on pull request closed events
on:
  pull_request:
    types: [ closed ]

jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - run: echo ${GITHUB_REF#refs/heads/}
    